### ISSUE TITLE
Escaped pipes still change color

### ISSUE THREAD

**Issue by annoyedhumanoid** [hieuthi/joplin-plugin-markdown-table-colorize#4]
The MultiMarkdown table extension, included in Joplin options as a Markdown plugin, enables support for escaped pipes using the character sequence `\|`. Markdown Table Colorize doesn't recognize that this pipe is escaped and changes color on that pipe character, even though the table does not change rows. Could this plugin recognize the escaped character and not switch colors?

**Comment by hieuthi** [comment]
I don't plan to support MultiMarkdown so I have no plan to fix it anytime soon, but I will leave this issue open in case I want to  support the escape character in the future.
