### ISSUE TITLE
Where do I add userchrome.css to change the colors?

### ISSUE THREAD

**Issue by zylont** [hieuthi/joplin-plugin-markdown-table-colorize#5]
I'm trying to change the colors/theme. Where do I add the userchrome.css file described in the Readme?

I'm running Joplin for Desktop on Windows 10 and I installed the plugin through the Joplin UI by going to Tools->Options->Plugins

**Comment by hieuthi** [comment]
I don’t remember the exact location of userchrome.css on Windows and I don’t have one to check at the moment, but you can follow the this official instruction to check the location.
https://joplinapp.org/help/apps/custom_css/

**Comment by zylont** [comment]
I found it. Thank you for pointing me in the right direction.  I didn't realize the userchrome.css was part of Joplin and not just part of the plugin. The top of the General page of the Configuration screen will show the exact path.
